server:
  port: 8080
spring:
  datasource:
    tasks:
      url: jdbc:postgresql://localhost:5432/eisetasks
      username: someuser
      password: somepassword
      driver-class-name: org.postgresql.Driver